import Foundation

enum AppVersion {
    static var current: String {
        Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String ?? "0.2"
    }

    static var display: String { "v\(current)" }
}

enum AppLanguage: String, CaseIterable, Identifiable {
    case system
    case chinese
    case english

    var id: String { rawValue }

    func resolved(preferredLanguages: [String] = Locale.preferredLanguages) -> AppLanguage {
        guard self == .system else { return self }
        return preferredLanguages.first?.lowercased().hasPrefix("zh") == true ? .chinese : .english
    }

    var locale: Locale {
        Locale(identifier: resolved() == .chinese ? "zh-Hans" : "en")
    }
}

enum AppLocalization {
    static func text(
        _ chinese: String,
        language: AppLanguage,
        _ arguments: [CVarArg] = []
    ) -> String {
        let template = language.resolved() == .chinese ? chinese : english[chinese, default: chinese]
        guard !arguments.isEmpty else { return template }
        return String(format: template, locale: language.locale, arguments: arguments)
    }

    private static let english: [String: String] = [
        "每小时平均额度按两次查询之间的时间计算，包含空闲时间；也可能包含其他设备的消耗。": "Hourly quota usage uses the time between queries, including idle time, and may include other devices.",
        "自动审查（未计入 Token 总数）": "Auto-review (excluded from total)",
        "统计说明": "About these statistics",
        "周期 / 总 Token": "Period / Total Tokens",
        "拖动以使用手动顺序（分组内排序）": "Drag to use manual order (within the group)",
        "切换进行中": "Switch in progress",
        "今日": "Today",
        "Token 明细": "Token breakdown",
        "用量统计": "Usage",
        "正在使用": "In use",
        "推荐备用": "Recommended",
        "切换到此账号": "Switch to this account",
        "5 小时剩余": "5-hour remaining",
        "周额度剩余": "Weekly remaining",
        "上次记录 · 需要重新登录": "Last recorded · Sign in again",
        "上次记录 · 重置 %@": "Last recorded · Resets %@",
        "添加账号后，可在这里查看额度和切换账号。": "Add an account to check its limits and switch accounts here.",
        "查看账号信息": "Account information",
        "查看详细信息": "View details",
        "API 等值估算": "API equivalent estimate",
        "API 等值估算 %@": "API equivalent estimate %@",
        "查看时段": "View period",
        "选择时段": "Select a period",
        "第 1 步 · 准备登录": "Step 1 · Prepare to sign in",
        "第 2 步 · 完成登录": "Step 2 · Complete sign-in",
        "观察记录": "Observations",
        "观察值不代表实际工作时长，也不会改变账号切换。": "Observations do not measure active work time or change account switching.",
        "输入": "Input",
        "缓存": "Cached",
        "输出": "Output",
        "推理": "Reasoning",
        "自动审查": "Auto-review",
        "分组": "Groups",
        "使用习惯": "Usage patterns",
        "Token 来自本机 Codex 记录，额度来自本应用刷新": "Tokens come from local Codex records; quota data comes from app refreshes",
        "统计范围": "Date range",
        "最近 30 天": "Last 30 days",
        "等待首次查询": "Waiting for the first query",
        "刷新账号额度后开始积累记录。启用自动查询可以持续采样，旧缓存不会补算成历史。": "Refresh account limits to start recording. Automatic refresh collects samples over time. Old cached values are not imported as history.",
        "这些记录能说明什么": "How to read these observations",
        "柱高表示所选时间内该小时使用的 Token 总量；柱顶数字表示其中有用量的天数。": "Bar height shows Token usage in that hour for the selected range; the number above shows days with usage.",
        "速度包含查询之间的空闲时间，不能直接当作实际工作速度；其他设备的消耗也可能计入。": "Rates include idle time between queries and are not active-work rates. Usage from other devices may also be included.",
        "超过 30 分钟的查询间隔、查询失败、跨窗口和额度回升不用于估算。百分比取整会使短期估计波动。": "Gaps over 30 minutes, failed queries, window resets and quota increases are excluded. Rounded percentages can make short-term estimates fluctuate.",
        "实际等待时间尚无法确定，不会把没有消耗自动记成休息，也不会据此改变账号切换。": "Actual waiting time is unknown. No usage is not automatically treated as a break, and these observations do not change account switching.",
        "正在积累观察记录": "Collecting observations",
        "已有使用观察，仍需持续校准": "Usage observed; estimates still need calibration",
        "对话次数": "Conversations",
        "采样天数": "Days sampled",
        "额度下降天数": "Days with quota decrease",
        "额度刷新失败次数": "Failed quota refreshes",
        "已记录 %d 次成功切换": "%d successful account changes recorded",
        "最近采样：%@": "Latest sample: %@",
        "各时段 Token 用量": "Token usage by hour",
        "%d 点：%d 天有用量，共 %@ Token": "Hour %d: usage on %d days, %@ Tokens total",
        "按本机时区汇总所选时间内的对话用量，单位为百万 Token。": "Conversation usage for the selected range, grouped in local time and measured in millions of Tokens.",
        "统计范围：%@ 至 %@": "Date range: %@ to %@",
        "总体额度观察": "Overall quota observations",
        "合并所有账号的数据": "All accounts combined",
        "额度记录 %d 次": "%d quota records",
        "每小时平均使用的 5h 额度": "Average 5h quota used per hour",
        "5h 额度对应周额度": "Weekly quota per 5h quota",
        "约 %.1f%%": "About %.1f%%",
        "数据不足": "Insufficient data",
        "另有 %d 组额度记录因重置、回升或相隔过久，未用于计算": "%d quota record pairs were excluded because of resets, increases, or long gaps",
        "额度使用习惯": "Quota usage patterns",
        "根据历次查询积累观察，不改变账号切换": "Learn from previous queries without changing account switching",
        "查看使用习惯": "View usage patterns",
        "无法保存使用历史，原文件已保留：%@": "Could not save usage history; the original file was preserved: %@",
        "无法读取使用历史，原文件已保留：%@": "Could not read usage history; the original file was preserved: %@",
        "准备就绪": "Ready",
        "准备添加新账号": "Ready to add an account",
        "设置": "Settings",
        "版本": "Version",
        "完成": "Done",
        "返回": "Back",
        "语言": "Language",
        "跟随系统": "Follow System",
        "中文": "中文",
        "英文": "English",
        "自动查询": "Automatic Refresh",
        "启用自动刷新": "Enable automatic refresh",
        "查询间隔": "Refresh interval",
        "刷新间隔": "Refresh interval",
        "间隔": "Interval",
        "单位": "Unit",
        "时间单位": "Time unit",
        "秒": "Seconds",
        "分钟": "Minutes",
        "自动查询默认每 1 分钟执行；可自定义秒或分钟。全量查询时账号之间间隔 1 秒，单账号查询立即执行。": "Automatic refresh runs every minute by default. You can choose seconds or minutes. Full refreshes wait one second between accounts; single-account refreshes run immediately.",
        "自动查询默认每 1 分钟执行；可自定义秒或分钟。全量查询时账号之间间隔 1 秒。": "Automatic refresh runs every minute by default. You can choose seconds or minutes. Full refreshes wait one second between accounts.",
        "打开设置": "Open Settings",
        "增加账号": "Add Account",
        "待查询": "Not yet queried",
        "刷新": "Refresh",
        "正在刷新": "Refreshing",
        "已载入 %d 个账号": "%d accounts loaded",
        "当前使用": "Current",
        "未识别": "Unknown",
        "切换": "Switch",
        "使用": "In Use",
        "下一个账号": "Next Account",
        "暂无可用账号": "No available account",
        "请刷新额度后重试": "Refresh usage and try again",
        "5 小时 %d%% · 周额度 %d%%": "5-hour %d%% · Weekly %d%%",
        "暂无额度信息": "No usage data",
        "所有账号": "All Accounts",
        "按分组显示": "Group Accounts",
        "更换分组": "Change Group",
        "管理分组": "Manage Groups",
        "创建、重命名分组，并批量调整账号归属": "Create and rename groups, or move accounts in batches",
        "未分组": "Ungrouped",
        "加入分组": "Add to Group",
        "切换分组": "Change Group",
        "要加入的分组": "Group to Join",
        "要切换的分组": "New Group",
        "替换组内账号": "Replace Account in Group",
        "不替换，仅加入此分组": "Do not replace; only join this group",
        "替换只会将所选账号移出当前分组，不会删除账号或登录凭证。": "Replacing only removes the selected account from this group. It does not delete the account or its sign-in credentials.",
        "新分组名称": "New group name",
        "创建分组": "Create Group",
        "编辑分组": "Edit Group",
        "目标分组": "Target Group",
        "分组名称": "Group name",
        "更新名称": "Rename",
        "删除分组": "Delete Group",
        "删除": "Delete",
        "选择要移动到此分组的账号": "Select accounts to move to this group",
        "已选择 %d 个": "%d selected",
        "未分组是默认分类，无需编辑": "Ungrouped is the default category and cannot be edited",
        "全选": "Select All",
        "清空": "Clear",
        "批量应用": "Apply to Selected",
        "已应用到 %d 个账号": "Applied to %d accounts",
        "删除分组后，组内账号将变为未分组，账号不会被删除。": "Accounts in this group will become ungrouped. No accounts will be deleted.",
        "无法读取账号分组：%@": "Could not read account groups: %@",
        "%d 个": "%d",
        "额度更新于 %@": "Usage updated %@",
        "5 小时": "5-hour",
        "周额度": "Weekly",
        "重置卡 %d 张": "Reset cards: %d",
        "重置 %@": "Resets %@",
        "立即查询此账号，不等待": "Refresh this account now",
        "登录已失效": "Sign-in expired",
        "重新登录": "Sign in again",
        "账号登录已失效，点击重新登录": "This account's sign-in has expired. Click to sign in again.",
        "重新登录 %@ 账号": "Sign in to %@ again",
        "准备重新登录 %@": "Ready to sign in to %@ again",
        "已恢复上次未完成的重新登录": "Recovered the previous interrupted sign-in",
        "无法恢复上次未完成的重新登录：%@": "Could not recover the previous interrupted sign-in: %@",
        "重新登录需要先安装 ChatGPT 或 Codex CLI。未修改任何账号文件。": "Install ChatGPT or Codex CLI before signing in again. No account files were changed.",
        "无法识别该账号原身份，不能安全替换凭据。": "The original account identity could not be verified, so its credentials were not replaced.",
        "请在 ChatGPT 中重新登录 %@。登录数据只保存在本机；本应用不会上传或展示登录凭据。": "Sign in to %@ again in ChatGPT. Login data stays on this Mac; this app never uploads or displays credentials.",
        "登录的账号与 %@ 不一致，请退出后重新登录正确账号。": "The signed-in account does not match %@. Sign out and sign in to the correct account.",
        "已重新登录 %@": "Signed in to %@ again",
        "已取消重新登录": "Cancelled sign-in",
        "重新登录失败，原账号已保留：%@": "Sign-in failed; the previous account was preserved: %@",
        "不会自动查询；重新登录后可手动刷新恢复。": "Automatic refresh is paused. Sign in again, then refresh manually.",
        "失效": "Expired",
        "当前账号登录状态已失效，是否重新登录？": "This account's sign-in has expired. Sign in again?",
        "重新登录后手动查询此账号": "Sign in again, then refresh this account manually",
        "账号操作": "Account actions",
        "拖动排序": "Drag to reorder",
        "清空排序条件后可拖动": "Clear sorting rules to drag",
        "排序 %d": "%d sort rules",
        "组合排序": "Combined Sorting",
        "从上到下依次比较；时间未知的账号始终排在最后。": "Rules are applied from top to bottom. Accounts with unknown reset times stay last.",
        "使用手动排序": "Using Manual Order",
        "升序": "Ascending",
        "降序": "Descending",
        "添加排序条件": "Add Sort Rule",
        "恢复手动排序": "Restore Manual Order",
        "周重置时间": "Weekly Reset Time",
        "5h重置时间": "5h Reset Time",
        "Token 统计": "Token Usage",
        "统计信息": "Summary",
        "账号明细": "Account Details",
        "金额": "Cost",
        "%@总 Token": "%@ Total Tokens",
        "%@总金额": "%@ Total Cost",
        "今日总 Token": "Today's Total Tokens",
        "本周总 Token": "This Week's Total Tokens",
        "本月总 Token": "This Month's Total Tokens",
        "排序": "Sort by",
        "账号排序": "Sort accounts by",
        "仅统计启用此功能后的本机记录": "Local records collected after this feature was enabled",
        "Credit 余额：$%.2f": "Credit balance: $%.2f",
        "Credit 余额：未启用": "Credit balance: Not enabled",
        "5h": "5h",
        "5h额度周期": "5h Quota Period",
        "5h额度": "5h Quota",
        "周": "Wk",
        "今天": "Today",
        "当前周": "Current week",
        "本周": "This week",
        "本月": "This month",
        "每日": "Daily",
        "每周": "Weekly",
        "每月": "Monthly",
        "历史 Token 用量": "Historical Token Usage",
        "历史金额": "Historical Cost",
        "包含缓存 Token，仅统计本机已记录的数据": "Includes cached tokens and only data recorded on this Mac",
        "按 OpenAI API 等值价格估算，仅统计本机已记录的数据": "Estimated at OpenAI API-equivalent prices using only data recorded on this Mac",
        "时间": "Time",
        "Token 用量": "Token usage",
        "%@ Token": "%@ tokens",
        "总 Token %@": "Total tokens %@",
        "全部用量均可估算": "All usage is priced",
        "部分用量无法估算": "Some usage cannot be priced",
        "还有其他用量无法估算": "Other usage also cannot be priced",
        "金额不包含 codex-auto-review": "Cost excludes codex-auto-review",
        "codex-auto-review %@（未计入总数）": "codex-auto-review %@ (excluded from total)",
        "周额度周期": "Weekly quota cycle",
        "周额度预测 $%.2f（依据 %d%% 用量）": "Weekly quota projection $%.2f (based on %d%% usage)",
        "周额度预测 $%.2f*（依据 %d%% 用量）": "Weekly quota projection $%.2f* (based on %d%% usage)",
        "预测 $%.2f · %d%%用量": "Projected $%.2f · %d%% used",
        "预测 $%.2f* · %d%%用量": "Projected $%.2f* · %d%% used",
        "周额度预测：暂无数据": "Weekly quota projection: No data",
        "暂无精确重置时间": "Exact reset time unavailable",
        "开始 %@\n重置 %@": "From %@\nResets %@",
        "开始 %@\n结束 %@": "From %@\nEnds %@",
        "总计 %@": "Total %@",
        "输入 %@ · 缓存 %@": "Input %@ · Cached %@",
        "输出 %@ · 推理 %@": "Output %@ · Reasoning %@",
        "输入 %@": "Input %@",
        "缓存 %@": "Cached %@",
        "输出 %@": "Output %@",
        "推理 %@": "Reasoning %@",
        "自动审查 %@": "Auto-review %@",
        "未计入 Token 总数": "Excluded from Token total",
        "（未计入 Token 总数）": "(Excluded from Token total)",
        "自动审查 %@（未计入 Token 总数）": "Auto-review %@ (excluded from Token total)",
        "柱形为 Token，用量金额标在柱形上方；仅统计本机已记录的数据": "Bars show Token usage; cost is labeled above each bar. Only locally recorded data is included",
        "%@ Token，金额 %@": "%@ tokens, cost %@",
        "价格为 OpenAI API 等值估算，使用美元。": "Prices are OpenAI API-equivalent estimates in USD.",
        "暂无法估算": "Estimate unavailable",
        "$%.4f（部分可估算）": "$%.4f (partial estimate)",
        "无法读取 Token 统计：%@": "Could not read token usage: %@",
        "切换记录": "Switch History",
        "账号切换": "Account Changes",
        "分组切换": "Group Changes",
        "仅保存在本机，最多保留 500 条": "Stored only on this Mac, up to 500 entries",
        "暂无切换记录": "No switch history",
        "完成账号切换、添加、重新登录或更换分组后会显示在这里。": "Completed switches, account additions, sign-ins, and group changes will appear here.",
        "暂无账号切换记录": "No account change history",
        "暂无分组切换记录": "No group change history",
        "完成账号切换、添加或重新登录后会显示在这里。": "Completed switches, account additions, and sign-ins will appear here.",
        "更换账号分组后会显示在这里。": "Account group changes will appear here.",
        "%@ → %@": "%@ → %@",
        "新增账号：%@": "Added account: %@",
        "新增账号：%@ · 加入 %@": "Added account: %@ · Joined %@",
        "重新登录：%@": "Signed in again: %@",
        "重新登录：%@ · 加入 %@": "Signed in again: %@ · Joined %@",
        "%@ → %@（重新登录）": "%@ → %@ (signed in again)",
        "%@：%@ → %@": "%@: %@ → %@",
        "成功": "Success",
        "失败": "Failed",
        "无法保存切换记录：%@": "Could not save switch history: %@",
        "设置别名": "Set Alias",
        "移除账号": "Remove Account",
        "切换账号": "Switch Account",
        "切换前请确认以下事项。": "Review these steps before switching.",
        "将账号切换到 %@": "Switch the account to %@",
        "确认后自动关闭": "Closes automatically after confirmation",
        "切换完成后自动重新打开": "Reopens automatically after switching",
        "切换前保存工作并退出": "Save your work and exit before switching",
        "切换完成后手动重新打开": "Reopen manually after switching",
        "如果你正在终端中使用 codex，请先保存并退出；如果不使用终端版 Codex，可直接继续。": "If you are using codex in Terminal, save your work and exit it first. If you do not use terminal-based Codex, you can continue.",
        "如果你在使用 Codex CLI，请手动重启；否则无需操作。": "If you use Codex CLI, restart it manually. Otherwise, no action is needed.",
        "ChatGPT（自动操作）": "ChatGPT (Automatic)",
        "Codex CLI（需手动关闭和重启）": "Codex CLI (Manual quit and restart)",
        "切换到 %@": "Switch to %@",
        "取消": "Cancel",
        "请先保存 ChatGPT 中的内容。确认后会关闭 ChatGPT，切换账号，再自动重新打开 ChatGPT。": "Save your work in ChatGPT first. ChatGPT will close, switch accounts, and reopen automatically.",
        "未检测到 ChatGPT。账号仍会正常切换，但不会自动打开 ChatGPT。": "ChatGPT was not found. The account will still switch, but ChatGPT will not open automatically.",
        "移到废纸篓": "Move to Trash",
        "账号凭据将移到废纸篓，可以恢复；不会永久删除。": "The account credentials will be moved to Trash and can be restored. They will not be permanently deleted.",
        "等待新账号登录": "Waiting for new account login",
        "增加 Codex 账号": "Add Codex Account",
        "取消后会关闭 ChatGPT 应用。": "Cancelling will close ChatGPT.",
        "取消后会关闭 ChatGPT 应用并恢复原账号。": "Cancelling will close ChatGPT and restore the previous account.",
        "取消后会恢复原账号。": "Cancelling will restore the previous account.",
        "先保存并退出所有正在运行的 Codex CLI": "Save your work and exit all running Codex CLI sessions",
        "继续后会关闭 ChatGPT，保留当前登录账号，只需在 ChatGPT 完成登录即可": "Continuing will close ChatGPT and preserve the current account. Complete sign-in in ChatGPT.",
        "继续后会保存当前账号，并等待你运行 codex login": "Continuing will save the current account and wait for you to run codex login",
        "正在恢复…": "Restoring…",
        "退出 ChatGPT 并继续": "Quit ChatGPT and Continue",
        "保存当前账号并继续": "Save Current Account and Continue",
        "设置账号别名": "Set Account Alias",
        "界面只显示别名；鼠标停留在别名上仍可查看用户名和邮箱。": "The interface shows the alias. Hover over it to see the username and email.",
        "别名": "Alias",
        "保存": "Save",
        "账号文件名：%@": "Account filename: %@",
        "用户名：%@\n邮箱：%@": "Username: %@\nEmail: %@",
        "请等待当前操作完成。": "Wait for the current operation to finish.",
        "添加账号前必须先切换到一个普通账号。": "Switch to a regular account before adding another account.",
        "新增账号需要先安装 ChatGPT。未修改任何账号文件。": "Install ChatGPT before adding an account. No account files were changed.",
        "正在检测 Codex CLI，请稍候。": "Detecting Codex CLI. Please wait.",
        "新增账号需要先安装 ChatGPT 或 Codex CLI。未修改任何账号文件。": "Install ChatGPT or Codex CLI before adding an account. No account files were changed.",
        "正在准备 Codex CLI 登录…": "Preparing Codex CLI sign-in…",
        "请打开终端运行 codex login，并在浏览器中完成登录。完成后请返回此处等待识别。": "Open Terminal, run codex login, and complete sign-in in your browser. Then return here and wait for detection.",
        "请先保存工作并退出所有正在运行的 Codex CLI。继续后，请在 ChatGPT 中登录新账号。": "Save your work and exit all running Codex CLI sessions. Then continue and sign in to the new account in ChatGPT.",
        "正在关闭 ChatGPT…": "Closing ChatGPT…",
        "请在 ChatGPT 中登录新账号。登录数据只保存在本机；本应用不会上传或展示登录凭据。": "Sign in to the new account in ChatGPT. Login data stays on this Mac; the app never uploads or displays credentials.",
        "已取消添加账号": "Account addition cancelled",
        "正在关闭登录窗口并恢复原账号…": "Closing the login window and restoring the original account…",
        "正在恢复原账号…": "Restoring the previous account…",
        "当前正在使用的账号不能移除，请先切换到其他账号。": "The account currently in use cannot be removed. Switch to another account first.",
        "账号已切换": "Account switched",
        "正在查询账号限额…": "Checking account usage…",
        "刷新完成": "Refresh complete",
        "刷新未完全成功": "Refresh did not fully complete",
        "账号查询失败": "Account refresh failed",
        "已刷新 %@": "Refreshed %@",
        "已恢复当前账号识别": "Current account identification restored",
        "已恢复上次未完成的新增账号": "Restored the account from the interrupted add-account flow",
        "已完成上次中断的新增账号": "Completed the interrupted add-account flow",
        "发现未完成的新增账号，但无法识别当前账号；现有凭据未修改。": "An interrupted add-account flow was found, but the current account could not be identified. Existing credentials were not changed.",
        "无法恢复上次未完成的新增账号：%@": "Could not restore the interrupted add-account flow: %@",
        "无法读取账号数据：%@": "Could not read account data: %@",
        "ChatGPT 未能关闭，请手动关闭后重试。账号文件未修改。": "ChatGPT could not be closed. Quit it manually and try again. Account files were not changed.",
        "添加失败，原账号已保留：%@": "Account addition failed; the original account was kept: %@",
        "恢复未完成：%@": "Restore did not complete: %@",
        "已将 %@ 的凭据移到废纸篓": "Moved %@ credentials to Trash",
        "移除失败：%@": "Removal failed: %@",
        "正在切换到 %@…": "Switching to %@…",
        "已切换到 %@，已打开 ChatGPT": "Switched to %@ and opened ChatGPT",
        "已切换到 %@，ChatGPT 未运行，已保持关闭": "Switched to %@; ChatGPT was not running and remains closed",
        "已切换到 %@，未检测到 ChatGPT，已跳过自动打开": "Switched to %@. ChatGPT was not found, so opening it was skipped.",
        "已切换账号，但无法打开 ChatGPT：%@": "The account was switched, but ChatGPT could not be opened: %@",
        "无法运行切换脚本：%@": "Could not run the switching script: %@",
        "已添加 %@": "Added %@",
        "切换失败": "Switch failed",
        "切换未开始": "Switch did not start",
        "账号": "Account",
        "周期": "Period",
        "总计": "Total",
        "价格": "Price",
        "输入 / 缓存": "Input / cached",
        "输出 / 推理": "Output / reasoning",
        "Credit 余额": "Credit balance",
        "未启用": "Not enabled",
        "Token 总计不包含 codex-auto-review，其用量单独标注。金额不包含 codex-auto-review；* 表示还有其他用量无法估算。": "Token totals exclude codex-auto-review, which is shown separately. Cost excludes codex-auto-review; * means other usage cannot be estimated.",
        "中转站": "Hub",
        "推荐": "Recommended",
        "暂无账号数据": "No account data",
        "点击“立即刷新”读取账号限额。": "Select Refresh to load account usage.",
        "最近更新：%@": "Last updated: %@",
        "切换到推荐账号": "Switch to Recommended Account",
        "5 小时额度": "5-hour Usage",
        "重置卡": "Reset Cards",
        "需要时可使用": "Available when needed",
        "当前没有可用重置卡": "No reset cards available",
        "重置：%@": "Resets: %@",
        "当前账号": "Current account"
    ]
}
